### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zhaijianyang** [AIM-SE/DIF-SR#10]
selected_features长度大于1会出现下面错误：

[copy.deepcopy(FeatureSeqEmbLayer(dataset,self.attribute_hidden_size[_],[self.selected_features[_]],self.pooling_mode,self.device)) for _
IndexError: list index out of range

**Comment by PALIN2018** [comment]
你好，请问可以给一个具体的错误例子吗？比如使用了哪个数据集的哪些特征，config是什么，以方便我们定位问题。
