### ISSUE TITLE
About AAP

### ISSUE THREAD

**Issue by jinweiluo** [AIM-SE/DIF-SR#5]
Hi, Thanks for your great work.

I would like to ask about the specific label used by AAP in DIF-SR ?
For example, in the Beauty dataset, I print out the categories label of each sample through the code, which is a sample corresponding to a 14-dimensional categories.
Does this ‘categories’ refer to the multi-level categories of the target item?
Whether the category used in the sequence level is a single value or the same 14 dimension value ？
And why ？

**Comment by PALIN2018** [comment]
Hi, for beauty dataset, each item might belong to multiple categories and 14 here is the max number of the categories for each item. For example, if an item belong to 5 categories, the RecBole will pad it to the length of 14. And we further represent these category information as 355 dimension vectors and each dimension denotes whether this item belongs to a specific category. Finally, we use these Multi-labels as supervision signals and adopt BCE loss to train AAP.
