### ISSUE TITLE
Failure to use multi-GPU setting

### ISSUE THREAD

**Issue by fenneccat** [AIM-SE/DIF-SR#8]
Hello, thank you for the code you posted.

There is a multi-GPU setting in the code, so I set the config like below
```
...
gpu_id: '0,1,2,3'
multi_gpus: True
...
```

In order to use multi-gpu, I used torchrun to run. I put the command as shown below.

`torchrun run_recbole.py --model=SASRecD --dataset='Amazon_Beauty' --config_files='configs/Amazon_Beauty.yaml' --nproc=4`

However, this kind of error occurs, which doesn't happen in a single GPU setting.

<img width="1264" alt="스크린샷 2023-03-07 오후 6 27 14" src="https://user-images.githubusercontent.com/22452009/223380198-e23bbd05-4e2f-4941-a697-fe9e6ad05ecb.png">

Can you tell me how can I use multi-gpu setting properly?
Does Multi-GPU setting not finished yet?

**Comment by fenneccat** [comment]
I edited below part in trainer.py
line 240: **interaction** => **interaction.interaction**
<img width="631" alt="스크린샷 2023-03-07 오후 7 42 41" src="https://user-images.githubusercontent.com/22452009/223399506-74476372-dc8b-497d-ae5c-47bdcab8fcd3.png">

and it runs.
However, it doesn't use other gpus in a node. Only gpu 0 is working.
Can you tell me how to use multi gpu with example of Amazon_Beauty?

<img width="601" alt="스크린샷 2023-03-07 오후 7 46 50" src="https://user-images.githubusercontent.com/22452009/223400575-c2b6f65c-4fa8-48d1-bb18-bc882389d705.png">

Thanks

**Comment by PALIN2018** [comment]
Hi fenneccat,

Thank you for your interest in our DIF project and for bringing up the issue regarding multi-GPU training. We appreciate your feedback and want to ensure that our code is as robust and user-friendly as possible.

Regarding the issue you raised, we would like to clarify that the code we have released on GitHub is based on an older version of RecBole, which does not support multi-GPU training. The multi-GPU code in our lab's implementation is experimental and may have some issues that we are still working on.

We recommend using the latest version of RecBole, as they have improved support for multi-GPU training and it will likely save you time and effort. We will also consider updating our DIF project code to use the latest version of RecBole in the future.

Once again, thank you for your interest in our project and for bringing this issue to our attention. Please feel free to reach out to us if you have any further questions or concerns.
